[tasks.objcopy]
command = "cargo"
args= [
    "objcopy",
    "--bin", "phm",
    "--release",
    "--",
    "-O", "binary",
    "target/thumbv6m-none-eabi/release/phm.bin"
]

[tasks.dfu]
command = "dfu-util"
args = [
    "-d", "0483:df11",
    "-a", "0",
    "-s", "0x08000000:leave",
    "-D", "target/thumbv6m-none-eabi/release/phm.bin"
]
dependencies = ["objcopy"]

[tasks.flash]
command = "openocd"
args = [
    "-f", "openocd.cfg",
    "-c", "program target/thumbv6m-none-eabi/release/phm reset"
]
